### ISSUE TITLE
stacks: okcomputer to replace is_it_working

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/digital_stacks_rails#96]
Exemplar:  purl-fetcher

possibly:
- `/status` endpoint for load-balancer needs and nagios errors
- `/status/[some-dependency]` for nagios warnings;  nagios routes them to approp parties
- `/status/all-dependencies` for full dependency documentation (?)

after this
- [x] PR merged to master (#97, #99, #101)
  - [x] deploy
- [x] update Load Balancer (SAR-3254)
- [ ] update nagios 
  - [x] basic checks (~~sul-dlss/puppet#1014~~, ~~sul-dlss/puppet#1015~~, ~~sul-dlss/puppet#1016~~, ~~sul-dlss/puppet#1017~~) 
  - [x] stacks-lb (sul-dlss/puppet/pull/1024)
  - [ ] any individual checks need separate nagios handling? (punt to #86)
- [x] remove is_it_working (#105)
  - [ ] deploy
    - [x] dev
    - [x] stage
    - [ ] uat
    - [x] prod
- [ ] update DevOpsDocs (sul-dlss/DevOpsDocs/pull/62)

**Comment by ndushay** [comment]
I'm closing this - the only remaining unchecked boxes either have separate issues or PRs.
